[colors.normal]
black = "0x95ffa4"

[font]
size = 11

[font.bold]
family = "fantasque sans mono"
style = "Bold"

[font.bold_italic]
family = "fantasque sans mono"
style = "Bold Italic"

[font.italic]
family = "fantasque sans mono"
style = "Italic"

[font.normal]
family = "fantasque sans mono"
style = "Regular"

[window]
opacity = 0.65
